version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: requests-cache
    versions:
    - 0.6.0
    - 0.6.1
    - 0.6.2
  - dependency-name: furl
    versions:
    - 2.1.1
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: responses
    versions:
    - 0.12.1
    - 0.13.1
    - 0.13.2
  - dependency-name: arrow
    versions:
    - 0.17.0
    - 1.0.0
    - 1.0.2
    - 1.0.3
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
