version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/python-annict
    steps:
      - checkout
      - run:
         name: Install poetry
         command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: echo 'export PATH=$HOME/.poetry/bin:$PATH' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: source $HOME/.poetry/env
      - run:
          name: Remove .pyc files
          command: find . -name \*.pyc -delete
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run Tests
          command: poetry run pytest tests --cov-report html:test-reports/coverage --cov annict -vv --junit-xml=test-reports/pytest.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
  py36:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/python-annict
    steps:
      - checkout
      - run:
         name: Install poetry
         command: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: echo 'export PATH=$HOME/.poetry/bin:$PATH' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: source $HOME/.poetry/env
      - run:
          name: Remove .pyc files
          command: find . -name \*.pyc -delete
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run Tests
          command: poetry run pytest tests --cov-report html:test-reports/coverage --cov annict -vv --junit-xml=test-reports/pytest.xml

workflows:
  version: 2
  py37:
    jobs:
      - build
  py36:
    jobs:
      - py36
