version: 2.1
commands:
  install_poetry:
    description: Install poetry
    steps:
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: echo 'export PATH=$HOME/.poetry/bin:$PATH' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: source $HOME/.poetry/env
  remove_pyc:
    description: Remove .pyc files
    steps:
      - run: find . -name \*.pyc -delete
  install_dependencies:
    description: Install dependencies
    steps:
      - run: poetry install
  pytest:
    description: Run pytest
    steps:
      - run: poetry run pytest tests --cov-report html:test-reports/coverage --cov annict -vv --junit-xml=test-reports/pytest.xml
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/python-annict
    steps:
      - checkout
      - install_poetry
      - remove_pyc
      - install_dependencies
      - pytest
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
  py36:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/python-annict
    steps:
      - checkout
      - checkout
      - install_poetry
      - remove_pyc
      - install_dependencies
      - pytest
workflows:
  version: 2
  py37:
    jobs:
      - build
  py36:
    jobs:
      - py36
