version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    working_directory: /home/ubuntu/python-annict
    steps:
      - checkout
      - run:
         name: Setup
         command: python setup.py install
      - run:
         name: Install pipenv
         command: pip install pipenv
      - run:
          name: Install Dependencies
          command: pipenv install -d
      - run:
          name: Remove .pyc files
          command: find . -name \*.pyc -delete
      - run:
          name: Run Tests
          command: pipenv run pytest tests --junit-xml=test-reports/pytest.xml --cov-report html:test-reports/coverage --cov annict -vv
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

